In [1]:
# The following is to know when this notebook has been run and with which python version.
import time, sys
print(time.ctime())
print(sys.version.split('|')[0])

Fri May  9 14:43:37 2025
3.11.5 (main, Sep 11 2023, 08:17:37) [Clang 14.0.6 ]

In [2]:
import numpy as np
import scipy

# F Some useful libraries that make life easier

This is part of the Python lecture given by Christophe Morisset at IA-UNAM.

This lecture will give some insights to the most useful python libraries. It is NOT exhaustive, you have to read the corresponding manual pages to find the best use you can have of them. The list of all python-included libraries is here: https://docs.python.org/3/library/

### time, datetime and timeit

*  https://docs.python.org/3/library/time.html
*  https://docs.python.org/3/library/datetime.html

In [3]:
import time
import datetime

In [4]:
print(time.ctime()) # current time, in a string format

Fri May  9 14:43:41 2025

In [5]:
lt = time.localtime()
print(lt)

time.struct_time(tm_year=2025, tm_mon=5, tm_mday=9, tm_hour=14, tm_min=43, tm_sec=41, tm_wday=4, tm_yday=129, tm_isdst=0)

In [6]:
time.strftime("%a, %d %b %Y %H:%M:%S",lt)

'Fri, 09 May 2025 14:43:41'

In [7]:
print(datetime.datetime.today())

2025-05-09 14:43:42.576562

In [8]:
today = datetime.date.today()
eclipse_total = datetime.date(2024, 4, 8)

In [9]:
time_to_eclipse = eclipse_total - today

In [10]:
if eclipse_total > today:
    print('Eclipse in {} days.'.format(time_to_eclipse.days))
else:
    print('Eclipse {} days ago.'.format(-time_to_eclipse.days))

Eclipse 396 days ago.

In [11]:
start = time.time()
for i in np.arange(1000):
    t = scipy.special.factorial(i)
end = time.time()
print(start, end)
print(f'1000 factorials done in {end-start:.3f} secs.')

1746823425.1733701 1746823425.4596832
1000 factorials done in 0.286 secs.

In [12]:
from timeit import Timer
command = """\
for i in range(1000):
    t = scipy.special.factorial(i)
"""
t = Timer(command, setup='import scipy')
print(t.timeit(number=10))

0.05738049999990835

in ipython, one can use the magic timeit function:

In [13]:
%timeit scipy.special.factorial(1000)

3.22 μs ± 24.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

or for the whole cell:

In [14]:
%%timeit
for i in np.arange(1000):
    t =  scipy.special.factorial(i)

3.18 ms ± 222 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

### os

https://docs.python.org/3/library/os.html 
This module provides a portable way of using operating system dependent functionality. If you just want to read or write a file see open(), if you want to manipulate paths, see the os.path module, and if you want to read all the lines in all the files on the command line see the fileinput module. For creating temporary files and directories see the tempfile module, and for high-level file and directory handling see the shutil module.

In [15]:
import os

In [16]:
# os.environ is a dictionnary containing the environment variables and values
if 'HOME' in os.environ:
    print(os.environ['HOME'])
else:
    print('This OS is too limited to understand HOME')

/Users/christophemorisset

In [17]:
# if variable doesn't exists, getenv returns None
print(os.getenv('HOMMMMMME'))

None

In [18]:
# get current working directory
cwd = os.getcwd()
print(cwd)
print(cwd.split('/')[-1])

/Users/christophemorisset/Google Drive/Pro/Python-MySQL/Python-lectures-Notebooks/Lecture_Notebooks
Lecture_Notebooks

In [19]:
new_dir = '/tmp/test3457'
if not os.path.exists(new_dir):
    os.mkdir(new_dir)
    print('Dir {} created'.format(new_dir))
else:
    print('Dir {} exists'.format(new_dir))

Dir /tmp/test3457 created

In [20]:
# list all the files from a directory
os.listdir(new_dir)

[]

In [21]:
os.chdir(new_dir)
os.getcwd()

'/private/tmp/test3457'

In [22]:
# Renaming files in a directory
os.chdir('/tmp')
open('a.txt', 'a').close()
open('b.txt', 'a').close()
open('c.text', 'a').close()
for filename in os.listdir('./'):
    #print(filename)
    base_file, ext = os.path.splitext(filename)
    #print(base_file, ext)
    if ext == '.txt':
        newname = base_file + '.exe'
        try:
            os.rename(filename, newname)
            print('file {0} renamed to {1}'.format(filename, newname))
        except:
            print('file {0} NOT renamed'.format(filename))
print('-'*20)
!ls
os.chdir(cwd)

file b.txt renamed to b.exe
file a.txt renamed to a.exe
--------------------
Firefox-Cache                      drivefs_ipc.501
MozillaUpdateLock-2656FF1E876E9973 drivefs_ipc.501_shell
UpdateLock-712DAF5A23ABECDC        logi.ghub.system_tray.connection
a.exe                              logi.ghub.updater.log
b.exe                              powerlog
c.text                             test3457
com.apple.launchd.6L8MP4zti1       tmp-mount-aw4Vzi

### glob

https://docs.python.org/3/library/glob.html

No tilde expansion is done, but *, ?, and character ranges expressed with [] will be correctly matched.

In [23]:
from glob import glob

In [24]:
os.chdir(cwd)

In [25]:
cwd

'/Users/christophemorisset/Google Drive/Pro/Python-MySQL/Python-lectures-Notebooks/Lecture_Notebooks'

In [26]:
ipynb_files = glob('*.ipynb')
print(ipynb_files)

['Calling Fortran.ipynb', 'Galaxies_classification.ipynb', 'Test-Install.ipynb', 'Using_SQLalchemy.ipynb', 'intro_Scipy.ipynb', 'ANN.ipynb', 'Parallel.ipynb', 'OOP.ipynb', 'Using_astropy.ipynb', 'Interact with files.ipynb', 'Useful_libraries.ipynb', 'intro_numpy.ipynb', 'intro_Python.ipynb', 'Redshifts_ai4neb.ipynb', 'intro_Matplotlib.ipynb', 'Optimization.ipynb', 'Evaluacion.ipynb', 'Redshifts.ipynb', 'Using_astroquery.ipynb']

glob is also included in pathlib, better use it from there:

### pathlib

https://docs.python.org/3/library/pathlib.html

In [27]:
from pathlib import Path

In [28]:
new_dir = Path('/tmp/test1236')
print(new_dir)
print(new_dir.name)
print(new_dir.parent)

/tmp/test1236
test1236
/tmp

In [29]:
new_dir = Path('/tmp') / Path('test1236')
print(new_dir)
print(new_dir.name)
print(new_dir.parent)

/tmp/test1236
test1236
/tmp

In [30]:
if not new_dir.exists():
    new_dir.mkdir() # may use exist_ok=True
    print('Dir {} created'.format(new_dir))
else:
    print('Dir {} exists'.format(new_dir))

Dir /tmp/test1236 created

In [31]:
current = Path('.')
for f in current.glob('*.ipynb'):
    print(f"{f} is {f.stem} + {f.suffix}")

Calling Fortran.ipynb is Calling Fortran + .ipynb
Galaxies_classification.ipynb is Galaxies_classification + .ipynb
Test-Install.ipynb is Test-Install + .ipynb
Using_SQLalchemy.ipynb is Using_SQLalchemy + .ipynb
intro_Scipy.ipynb is intro_Scipy + .ipynb
ANN.ipynb is ANN + .ipynb
Parallel.ipynb is Parallel + .ipynb
OOP.ipynb is OOP + .ipynb
Using_astropy.ipynb is Using_astropy + .ipynb
Interact with files.ipynb is Interact with files + .ipynb
Useful_libraries.ipynb is Useful_libraries + .ipynb
intro_numpy.ipynb is intro_numpy + .ipynb
intro_Python.ipynb is intro_Python + .ipynb
Redshifts_ai4neb.ipynb is Redshifts_ai4neb + .ipynb
intro_Matplotlib.ipynb is intro_Matplotlib + .ipynb
Optimization.ipynb is Optimization + .ipynb
Evaluacion.ipynb is Evaluacion + .ipynb
Redshifts.ipynb is Redshifts + .ipynb
Using_astroquery.ipynb is Using_astroquery + .ipynb

In [32]:
new_dir = Path('/tmp') / Path('test1236')
for f in new_dir.glob('test*.txt*'):
    f.unlink() # remove file

f = new_dir / Path('test1234.txt')
f.touch()
f = new_dir / Path('test5678.txt')
f.touch()
print([f.name for f in new_dir.glob('test*.txt*')])

for f in new_dir.glob('test*.txt'):
    new_f = f.with_suffix('.txt2')
    if not new_f.exists():
        f.rename(new_f)
    else:
        print('{} exists'.format(new_f))

print([f.name for f in new_dir.glob('test*.txt*')])

['test5678.txt', 'test1234.txt']
['test1234.txt2', 'test5678.txt2']

### sys

In [33]:
pwd

'/Users/christophemorisset/Google Drive/Pro/Python-MySQL/Python-lectures-Notebooks/Lecture_Notebooks'

https://docs.python.org/3/library/sys.html
This module provides access to some variables used or maintained by the interpreter and to functions that interact strongly with the interpreter. It is always available.

The sys.argv list contains the arguments passed to the script, when the interpreter was started. The first item contains the name of the script itself.

In [34]:
%%writefile sys_text.py
import sys
for arg in sys.argv:
    print(arg)

Overwriting sys_text.py

In [35]:
!cat sys_text.py

import sys
for arg in sys.argv:
    print(arg)

In [36]:
! python sys_text.py tralala trololo 1234

sys_text.py
tralala
trololo
1234

In [37]:
%%writefile fact.py
import sys
import scipy
print(scipy.special.factorial(int(sys.argv[1])))

Writing fact.py

In [38]:
! python fact.py 60

8.32098711274139e+81

A more complete managment of the argument (especially those like --v) is available using the argparse library. https://docs.python.org/3/library/argparse.html

### Talking to the OS subprocess

The os.popen method is deprecated, subprocess is prefered. https://docs.python.org/3/library/subprocess.html . A good tutorial is here: http://pymotw.com/3/subprocess/

In [1]:
import subprocess

In [6]:
var0 = subprocess.run(['ls', '-l'])

total 132848
-rw-------@ 1 christophemorisset  staff     89353 Apr 21  2025 0040000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     85600 Apr 22  2025 0050000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     86018 May  9  2025 0050000_7.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     86741 Apr 22  2025 0060000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     88843 Apr 22  2025 0070000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89360 Apr 22  2025 0080000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89971 Apr 21  2025 0090000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89722 Apr 22  2025 0100000_5.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     90544 Apr 22  2025 0100000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     91192 Apr 22  2025 0100000_7.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     91475 Apr 22  2025 0100000_8.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     90430 Apr 22  2025 0110000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     90960 May  9  2025 0110000_7.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89525 Apr 22  2025 0120000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89899 Apr 22  2025 0130000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89170 Apr 21  2025 0140000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89263 Apr 22  2025 0150000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     88929 Apr 22  2025 0160000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     88991 Apr 22  2025 0170000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     88780 Apr 22  2025 0180000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89075 Apr 22  2025 0180000_7.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     88591 Apr 21  2025 0190000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff    960204 May 14  2025 ANN.ipynb
-rw-------@ 1 christophemorisset  staff    173771 May  5  2025 ANN_1_2.png
-rw-------@ 1 christophemorisset  staff     20137 Feb 11  2025 Calling Fortran.ipynb
-rw-------@ 1 christophemorisset  staff     86815 Feb 11  2025 Calling Fortran.pdf
-rw-------@ 1 christophemorisset  staff   3892947 Mar 26 11:50 DR9_photo-z-small.csv.gz
-rw-------@ 1 christophemorisset  staff       217 Feb 25  2025 Demo.pickle
-rw-------@ 1 christophemorisset  staff       194 Feb 25  2025 Demo.pklz
-rw-------@ 1 christophemorisset  staff       445 Feb 11  2025 Evaluacion.ipynb
-rw-------@ 1 christophemorisset  staff    120910 Apr 14 13:47 Fig1.pdf
-rw-------@ 1 christophemorisset  staff   2466314 May 20  2025 Galaxies_classification.ipynb
-rw-------@ 1 christophemorisset  staff   1177040 Feb 11  2025 HII.dat
-rw-------@ 1 christophemorisset  staff    853215 Feb 11  2025 InstallPython.key
-rw-------@ 1 christophemorisset  staff    716796 Apr 14 14:12 Interact with files.ipynb
-rw-------@ 1 christophemorisset  staff    432747 Feb 11  2025 Interact with files.pdf
-rw-------@ 1 christophemorisset  staff    131497 Feb 11  2025 Intro_1.odp
-rw-------@ 1 christophemorisset  staff    174202 Feb 11  2025 Intro_1.pdf
-rw-------@ 1 christophemorisset  staff   1477306 Feb 11  2025 Machine Learning.pdf
-rw-------@ 1 christophemorisset  staff     52571 Apr 28  2025 MySQL.odp
-rw-------@ 1 christophemorisset  staff    104600 Apr 28  2025 MySQL.pdf
-rw-------@ 1 christophemorisset  staff   1332565 May  9  2025 OOP.ipynb
-rw-------@ 1 christophemorisset  staff    536767 Feb 11  2025 OOP.pdf
-rw-------@ 1 christophemorisset  staff     81850 May  9  2025 Optimization.ipynb
-rw-------@ 1 christophemorisset  staff    481656 Feb 11  2025 Optimization.pdf
-rw-------@ 1 christophemorisset  staff      2537 Feb 11  2025 Parallel.ipynb
-rw-------@ 1 christophemorisset  staff   1679352 May 13  2025 Redshifts.ipynb
-rw-------@ 1 christophemorisset  staff    999554 May  5  2025 Redshifts_ai4neb.ipynb
-rw-------@ 1 christophemorisset  staff      1434 Feb 11  2025 Test-Install.ipynb
-rw-------@ 1 christophemorisset  staff    124421 Apr 28 14:29 Useful_libraries.ipynb
-rw-------@ 1 christophemorisset  staff    514073 Feb 11  2025 Useful_libraries.pdf
-rw-------@ 1 christophemorisset  staff    207646 May  9  2025 Using_SQLalchemy.ipynb
-rw-------@ 1 christophemorisset  staff     80302 Feb 11  2025 Using_SQLalchemy.pdf
-rw-------@ 1 christophemorisset  staff    293519 May  9  2025 Using_astropy.ipynb
-rw-------@ 1 christophemorisset  staff    208399 Feb 11  2025 Using_astropy.pdf
-rw-------@ 1 christophemorisset  staff    165828 May  9  2025 Using_astroquery.ipynb
-rw-------@ 1 christophemorisset  staff    120503 Apr 28  2025 Using_astroquery.pdf
drwx------@ 6 christophemorisset  staff       192 Jan 25 00:28 __pycache__
-rw-------@ 1 christophemorisset  staff       114 Apr 21  2025 call_test_2_err.py
-rw-------@ 1 christophemorisset  staff  14794880 Feb 11  2025 cosmo-early.npy
-rw-------@ 1 christophemorisset  staff  14794880 Feb 11  2025 cosmo-late.npy
-rw-------@ 1 christophemorisset  staff        65 Mar 20 11:21 data1.dat
-rw-------@ 1 christophemorisset  staff        14 Feb 25  2025 data10.dat
-rw-------@ 1 christophemorisset  staff        32 Mar 20 13:14 data11.dat
-rw-------@ 1 christophemorisset  staff        16 Feb 25  2025 data11.dat.gz
-rw-------@ 1 christophemorisset  staff       148 Mar 20 13:17 data12.dat
-rw-------@ 1 christophemorisset  staff       148 Mar 20 11:50 data2.dat
-rw-------@ 1 christophemorisset  staff       165 Mar 20 12:34 data3.dat
-rw-------@ 1 christophemorisset  staff      1188 Mar 20 12:56 data4.dat
-rw-------@ 1 christophemorisset  staff      1186 Mar 20 13:02 data5.dat
-rw-------@ 1 christophemorisset  staff      1187 Mar 31  2025 data6.dat
-rw-------@ 1 christophemorisset  staff       364 Mar 23 10:56 data7.dat
-rw-------@ 1 christophemorisset  staff       298 Feb 11  2025 dcumsum.f
-rw-------@ 1 christophemorisset  staff       294 May 13  2025 env_FH_Python_Lecture_ML.yml
-rw-------@ 1 christophemorisset  staff      1344 Feb 17 13:37 ex1.html
-rw-------@ 1 christophemorisset  staff       159 Feb 17 12:56 ex1.py
-rw-------@ 1 christophemorisset  staff      6319 Feb 11  2025 grep3.py
-rw-------@ 1 christophemorisset  staff        49 Feb 11  2025 hello.py
-rw-------@ 1 christophemorisset  staff      1090 Feb 11  2025 hellofortran.c
-rw-------@ 1 christophemorisset  staff       178 Feb 11  2025 hellofortran.f
-rw-------@ 1 christophemorisset  staff     33976 Feb 11  2025 hellofortran.so
-rw-------@ 1 christophemorisset  staff       150 Feb 11  2025 index.html
-rw-------@ 1 christophemorisset  staff   5789181 Apr 14 14:12 intro_Matplotlib.ipynb
-rw-------@ 1 christophemorisset  staff   1677612 Feb 11  2025 intro_Matplotlib.pdf
-rw-------@ 1 christophemorisset  staff    326924 Feb 11  2025 intro_Python.html
-rw-------@ 1 christophemorisset  staff    117119 Mar  3 10:23 intro_Python.ipynb
-rw-------@ 1 christophemorisset  staff    119242 Feb 11  2025 intro_Python.pdf
-rw-------@ 1 christophemorisset  staff    998960 Apr 21 15:22 intro_Scipy.ipynb
-rw-------@ 1 christophemorisset  staff    683346 Feb 11  2025 intro_Scipy.pdf
-rw-------@ 1 christophemorisset  staff    127341 Mar 19 13:29 intro_numpy.ipynb
-rw-------@ 1 christophemorisset  staff    128064 Feb 11  2025 intro_numpy.pdf
drwx------@ 3 christophemorisset  staff        96 Jan 25 00:28 mastDownload
-rw-------@ 1 christophemorisset  staff   8830080 Feb 11  2025 n10017o.fits
-rw-------@ 1 christophemorisset  staff      5760 Feb 25  2025 new.fits
-rw-------@ 1 christophemorisset  staff   1779169 May  9  2025 profile.html
-rw-------@ 1 christophemorisset  staff    180869 May  9  2025 profile.json
-rw-------@ 1 christophemorisset  staff    435801 Feb 11  2025 query_res.dat
-rw-------@ 1 christophemorisset  staff   1538466 Apr 14 13:47 scatter.pdf
-rw-------@ 1 christophemorisset  staff    135367 Apr 14 13:47 scatter.png
-rw-------@ 1 christophemorisset  staff    905924 Apr 14 13:47 scatter3.png
-rw-------@ 1 christophemorisset  staff   3892934 May  5  2025 sdss.csv.gz
-rw-------@ 1 christophemorisset  staff   1059840 Feb 11  2025 swp04345.mxhi
-rw-------@ 1 christophemorisset  staff        47 May  9  2025 sys_text.py
-rw-------@ 1 christophemorisset  staff       354 Mar 24  2025 tab1.dat
-rw-------@ 1 christophemorisset  staff       668 May  5  2025 tab_cds1.ascii
-rw-------@ 1 christophemorisset  staff     43200 Feb 11  2025 tab_cds1.fits
-rw-------@ 1 christophemorisset  staff      1334 Mar 24  2025 tab_cds1.tex
-rw-------@ 1 christophemorisset  staff      1826 May  5  2025 tab_cds2.ascii
-rw-------@ 1 christophemorisset  staff       455 Mar 31  2025 table.html
-rw-------@ 1 christophemorisset  staff      6728 May  9  2025 test_1_prof.py
-rw-------@ 1 christophemorisset  staff      6552 Apr 21  2025 test_2_err.py
-rw-------@ 1 christophemorisset  staff      6527 Apr 21  2025 test_4.py
-rw-------@ 1 christophemorisset  staff       166 May  9  2025 test_me.py
-rw-------@ 1 christophemorisset  staff       318 Apr 22  2025 test_pyneb.py

In [7]:
print(var0)

CompletedProcess(args=['ls', '-l'], returncode=0)

In [8]:
var0 = subprocess.run(['ls', '-l'], capture_output=True, text=True)

In [12]:
print(var0)

CompletedProcess(args=['ls', '-l'], returncode=0, stdout='total 132848\n-rw-------@ 1 christophemorisset  staff     89353 Apr 21  2025 \x1b[30m\x1b[47m0040000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     85600 Apr 22  2025 \x1b[30m\x1b[47m0050000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     86018 May  9  2025 \x1b[30m\x1b[47m0050000_7.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     86741 Apr 22  2025 \x1b[30m\x1b[47m0060000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     88843 Apr 22  2025 \x1b[30m\x1b[47m0070000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     89360 Apr 22  2025 \x1b[30m\x1b[47m0080000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     89971 Apr 21  2025 \x1b[30m\x1b[47m0090000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     89722 Apr 22  2025 \x1b[30m\x1b[47m0100000_5.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     90544 Apr 22  2025 \x1b[30m\x1b[47m0100000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     91192 Apr 22  2025 \x1b[30m\x1b[47m0100000_7.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     91475 Apr 22  2025 \x1b[30m\x1b[47m0100000_8.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     90430 Apr 22  2025 \x1b[30m\x1b[47m0110000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     90960 May  9  2025 \x1b[30m\x1b[47m0110000_7.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     89525 Apr 22  2025 \x1b[30m\x1b[47m0120000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     89899 Apr 22  2025 \x1b[30m\x1b[47m0130000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     89170 Apr 21  2025 \x1b[30m\x1b[47m0140000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     89263 Apr 22  2025 \x1b[30m\x1b[47m0150000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     88929 Apr 22  2025 \x1b[30m\x1b[47m0160000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     88991 Apr 22  2025 \x1b[30m\x1b[47m0170000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     88780 Apr 22  2025 \x1b[30m\x1b[47m0180000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     89075 Apr 22  2025 \x1b[30m\x1b[47m0180000_7.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     88591 Apr 21  2025 \x1b[30m\x1b[47m0190000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff    960204 May 14  2025 ANN.ipynb\n-rw-------@ 1 christophemorisset  staff    173771 May  5  2025 ANN_1_2.png\n-rw-------@ 1 christophemorisset  staff     20137 Feb 11  2025 Calling Fortran.ipynb\n-rw-------@ 1 christophemorisset  staff     86815 Feb 11  2025 Calling Fortran.pdf\n-rw-------@ 1 christophemorisset  staff   3892947 Mar 26 11:50 DR9_photo-z-small.csv.gz\n-rw-------@ 1 christophemorisset  staff       217 Feb 25  2025 \x1b[30m\x1b[47mDemo.pickle\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       194 Feb 25  2025 \x1b[30m\x1b[47mDemo.pklz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       445 Feb 11  2025 Evaluacion.ipynb\n-rw-------@ 1 christophemorisset  staff    120910 Apr 14 13:47 \x1b[30m\x1b[47mFig1.pdf\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff   2466314 May 20  2025 Galaxies_classification.ipynb\n-rw-------@ 1 christophemorisset  staff   1177040 Feb 11  2025 \x1b[30m\x1b[47mHII.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff    853215 Feb 11  2025 InstallPython.key\n-rw-------@ 1 christophemorisset  staff    716796 Apr 14 14:12 Interact with files.ipynb\n-rw-------@ 1 christophemorisset  staff    432747 Feb 11  2025 Interact with files.pdf\n-rw-------@ 1 christophemorisset  staff    131497 Feb 11  2025 Intro_1.odp\n-rw-------@ 1 christophemorisset  staff    174202 Feb 11  2025 Intro_1.pdf\n-rw-------@ 1 christophemorisset  staff   1477306 Feb 11  2025 Machine Learning.pdf\n-rw-------@ 1 christophemorisset  staff     52571 Apr 28  2025 MySQL.odp\n-rw-------@ 1 christophemorisset  staff    104600 Apr 28  2025 MySQL.pdf\n-rw-------@ 1 christophemorisset  staff   1332565 May  9  2025 OOP.ipynb\n-rw-------@ 1 christophemorisset  staff    536767 Feb 11  2025 OOP.pdf\n-rw-------@ 1 christophemorisset  staff     81850 May  9  2025 Optimization.ipynb\n-rw-------@ 1 christophemorisset  staff    481656 Feb 11  2025 Optimization.pdf\n-rw-------@ 1 christophemorisset  staff      2537 Feb 11  2025 Parallel.ipynb\n-rw-------@ 1 christophemorisset  staff   1679352 May 13  2025 Redshifts.ipynb\n-rw-------@ 1 christophemorisset  staff    999554 May  5  2025 Redshifts_ai4neb.ipynb\n-rw-------@ 1 christophemorisset  staff      1434 Feb 11  2025 \x1b[30m\x1b[47mTest-Install.ipynb\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff    124705 Apr 28 14:29 Useful_libraries.ipynb\n-rw-------@ 1 christophemorisset  staff    514073 Feb 11  2025 Useful_libraries.pdf\n-rw-------@ 1 christophemorisset  staff    207646 May  9  2025 Using_SQLalchemy.ipynb\n-rw-------@ 1 christophemorisset  staff     80302 Feb 11  2025 Using_SQLalchemy.pdf\n-rw-------@ 1 christophemorisset  staff    293519 May  9  2025 Using_astropy.ipynb\n-rw-------@ 1 christophemorisset  staff    208399 Feb 11  2025 Using_astropy.pdf\n-rw-------@ 1 christophemorisset  staff    165828 May  9  2025 Using_astroquery.ipynb\n-rw-------@ 1 christophemorisset  staff    120503 Apr 28  2025 Using_astroquery.pdf\ndrwx------@ 6 christophemorisset  staff       192 Jan 25 00:28 \x1b[34m__pycache__\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       114 Apr 21  2025 call_test_2_err.py\n-rw-------@ 1 christophemorisset  staff  14794880 Feb 11  2025 cosmo-early.npy\n-rw-------@ 1 christophemorisset  staff  14794880 Feb 11  2025 cosmo-late.npy\n-rw-------@ 1 christophemorisset  staff        65 Mar 20 11:21 \x1b[30m\x1b[47mdata1.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff        14 Feb 25  2025 \x1b[30m\x1b[47mdata10.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff        32 Mar 20 13:14 \x1b[30m\x1b[47mdata11.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff        16 Feb 25  2025 \x1b[30m\x1b[47mdata11.dat.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       148 Mar 20 13:17 \x1b[30m\x1b[47mdata12.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       148 Mar 20 11:50 \x1b[30m\x1b[47mdata2.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       165 Mar 20 12:34 \x1b[30m\x1b[47mdata3.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff      1188 Mar 20 12:56 \x1b[30m\x1b[47mdata4.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff      1186 Mar 20 13:02 \x1b[30m\x1b[47mdata5.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff      1187 Mar 31  2025 \x1b[30m\x1b[47mdata6.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       364 Mar 23 10:56 \x1b[30m\x1b[47mdata7.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       298 Feb 11  2025 dcumsum.f\n-rw-------@ 1 christophemorisset  staff       294 May 13  2025 env_FH_Python_Lecture_ML.yml\n-rw-------@ 1 christophemorisset  staff      1344 Feb 17 13:37 \x1b[30m\x1b[47mex1.html\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       159 Feb 17 12:56 \x1b[30m\x1b[47mex1.py\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff      6319 Feb 11  2025 grep3.py\n-rw-------@ 1 christophemorisset  staff        49 Feb 11  2025 hello.py\n-rw-------@ 1 christophemorisset  staff      1090 Feb 11  2025 hellofortran.c\n-rw-------@ 1 christophemorisset  staff       178 Feb 11  2025 hellofortran.f\n-rw-------@ 1 christophemorisset  staff     33976 Feb 11  2025 \x1b[30m\x1b[47mhellofortran.so\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       150 Feb 11  2025 index.html\n-rw-------@ 1 christophemorisset  staff   5789181 Apr 14 14:12 intro_Matplotlib.ipynb\n-rw-------@ 1 christophemorisset  staff   1677612 Feb 11  2025 intro_Matplotlib.pdf\n-rw-------@ 1 christophemorisset  staff    326924 Feb 11  2025 intro_Python.html\n-rw-------@ 1 christophemorisset  staff    117119 Mar  3 10:23 intro_Python.ipynb\n-rw-------@ 1 christophemorisset  staff    119242 Feb 11  2025 intro_Python.pdf\n-rw-------@ 1 christophemorisset  staff    998960 Apr 21 15:22 intro_Scipy.ipynb\n-rw-------@ 1 christophemorisset  staff    683346 Feb 11  2025 intro_Scipy.pdf\n-rw-------@ 1 christophemorisset  staff    127341 Mar 19 13:29 intro_numpy.ipynb\n-rw-------@ 1 christophemorisset  staff    128064 Feb 11  2025 intro_numpy.pdf\ndrwx------@ 3 christophemorisset  staff        96 Jan 25 00:28 \x1b[34mmastDownload\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff   8830080 Feb 11  2025 n10017o.fits\n-rw-------@ 1 christophemorisset  staff      5760 Feb 25  2025 new.fits\n-rw-------@ 1 christophemorisset  staff   1779169 May  9  2025 \x1b[30m\x1b[47mprofile.html\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff    180869 May  9  2025 \x1b[30m\x1b[47mprofile.json\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff    435801 Feb 11  2025 \x1b[30m\x1b[47mquery_res.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff   1538466 Apr 14 13:47 \x1b[30m\x1b[47mscatter.pdf\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff    135367 Apr 14 13:47 \x1b[30m\x1b[47mscatter.png\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff    905924 Apr 14 13:47 \x1b[30m\x1b[47mscatter3.png\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff   3892934 May  5  2025 \x1b[30m\x1b[47msdss.csv.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff   1059840 Feb 11  2025 swp04345.mxhi\n-rw-------@ 1 christophemorisset  staff        47 May  9  2025 sys_text.py\n-rw-------@ 1 christophemorisset  staff       354 Mar 24  2025 \x1b[30m\x1b[47mtab1.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       668 May  5  2025 tab_cds1.ascii\n-rw-------@ 1 christophemorisset  staff     43200 Feb 11  2025 tab_cds1.fits\n-rw-------@ 1 christophemorisset  staff      1334 Mar 24  2025 tab_cds1.tex\n-rw-------@ 1 christophemorisset  staff      1826 May  5  2025 tab_cds2.ascii\n-rw-------@ 1 christophemorisset  staff       455 Mar 31  2025 table.html\n-rw-------@ 1 christophemorisset  staff      6728 May  9  2025 \x1b[30m\x1b[47mtest_1_prof.py\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff      6552 Apr 21  2025 \x1b[30m\x1b[47mtest_2_err.py\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff      6527 Apr 21  2025 \x1b[30m\x1b[47mtest_4.py\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       166 May  9  2025 \x1b[30m\x1b[47mtest_me.py\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       318 Apr 22  2025 \x1b[30m\x1b[47mtest_pyneb.py\x1b[m\x1b[m\n', stderr='')

In [10]:
print(var0.stdout)

total 132848
-rw-------@ 1 christophemorisset  staff     89353 Apr 21  2025 0040000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     85600 Apr 22  2025 0050000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     86018 May  9  2025 0050000_7.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     86741 Apr 22  2025 0060000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     88843 Apr 22  2025 0070000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89360 Apr 22  2025 0080000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89971 Apr 21  2025 0090000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89722 Apr 22  2025 0100000_5.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     90544 Apr 22  2025 0100000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     91192 Apr 22  2025 0100000_7.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     91475 Apr 22  2025 0100000_8.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     90430 Apr 22  2025 0110000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     90960 May  9  2025 0110000_7.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89525 Apr 22  2025 0120000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89899 Apr 22  2025 0130000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89170 Apr 21  2025 0140000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89263 Apr 22  2025 0150000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     88929 Apr 22  2025 0160000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     88991 Apr 22  2025 0170000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     88780 Apr 22  2025 0180000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89075 Apr 22  2025 0180000_7.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     88591 Apr 21  2025 0190000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff    960204 May 14  2025 ANN.ipynb
-rw-------@ 1 christophemorisset  staff    173771 May  5  2025 ANN_1_2.png
-rw-------@ 1 christophemorisset  staff     20137 Feb 11  2025 Calling Fortran.ipynb
-rw-------@ 1 christophemorisset  staff     86815 Feb 11  2025 Calling Fortran.pdf
-rw-------@ 1 christophemorisset  staff   3892947 Mar 26 11:50 DR9_photo-z-small.csv.gz
-rw-------@ 1 christophemorisset  staff       217 Feb 25  2025 Demo.pickle
-rw-------@ 1 christophemorisset  staff       194 Feb 25  2025 Demo.pklz
-rw-------@ 1 christophemorisset  staff       445 Feb 11  2025 Evaluacion.ipynb
-rw-------@ 1 christophemorisset  staff    120910 Apr 14 13:47 Fig1.pdf
-rw-------@ 1 christophemorisset  staff   2466314 May 20  2025 Galaxies_classification.ipynb
-rw-------@ 1 christophemorisset  staff   1177040 Feb 11  2025 HII.dat
-rw-------@ 1 christophemorisset  staff    853215 Feb 11  2025 InstallPython.key
-rw-------@ 1 christophemorisset  staff    716796 Apr 14 14:12 Interact with files.ipynb
-rw-------@ 1 christophemorisset  staff    432747 Feb 11  2025 Interact with files.pdf
-rw-------@ 1 christophemorisset  staff    131497 Feb 11  2025 Intro_1.odp
-rw-------@ 1 christophemorisset  staff    174202 Feb 11  2025 Intro_1.pdf
-rw-------@ 1 christophemorisset  staff   1477306 Feb 11  2025 Machine Learning.pdf
-rw-------@ 1 christophemorisset  staff     52571 Apr 28  2025 MySQL.odp
-rw-------@ 1 christophemorisset  staff    104600 Apr 28  2025 MySQL.pdf
-rw-------@ 1 christophemorisset  staff   1332565 May  9  2025 OOP.ipynb
-rw-------@ 1 christophemorisset  staff    536767 Feb 11  2025 OOP.pdf
-rw-------@ 1 christophemorisset  staff     81850 May  9  2025 Optimization.ipynb
-rw-------@ 1 christophemorisset  staff    481656 Feb 11  2025 Optimization.pdf
-rw-------@ 1 christophemorisset  staff      2537 Feb 11  2025 Parallel.ipynb
-rw-------@ 1 christophemorisset  staff   1679352 May 13  2025 Redshifts.ipynb
-rw-------@ 1 christophemorisset  staff    999554 May  5  2025 Redshifts_ai4neb.ipynb
-rw-------@ 1 christophemorisset  staff      1434 Feb 11  2025 Test-Install.ipynb
-rw-------@ 1 christophemorisset  staff    124705 Apr 28 14:29 Useful_libraries.ipynb
-rw-------@ 1 christophemorisset  staff    514073 Feb 11  2025 Useful_libraries.pdf
-rw-------@ 1 christophemorisset  staff    207646 May  9  2025 Using_SQLalchemy.ipynb
-rw-------@ 1 christophemorisset  staff     80302 Feb 11  2025 Using_SQLalchemy.pdf
-rw-------@ 1 christophemorisset  staff    293519 May  9  2025 Using_astropy.ipynb
-rw-------@ 1 christophemorisset  staff    208399 Feb 11  2025 Using_astropy.pdf
-rw-------@ 1 christophemorisset  staff    165828 May  9  2025 Using_astroquery.ipynb
-rw-------@ 1 christophemorisset  staff    120503 Apr 28  2025 Using_astroquery.pdf
drwx------@ 6 christophemorisset  staff       192 Jan 25 00:28 __pycache__
-rw-------@ 1 christophemorisset  staff       114 Apr 21  2025 call_test_2_err.py
-rw-------@ 1 christophemorisset  staff  14794880 Feb 11  2025 cosmo-early.npy
-rw-------@ 1 christophemorisset  staff  14794880 Feb 11  2025 cosmo-late.npy
-rw-------@ 1 christophemorisset  staff        65 Mar 20 11:21 data1.dat
-rw-------@ 1 christophemorisset  staff        14 Feb 25  2025 data10.dat
-rw-------@ 1 christophemorisset  staff        32 Mar 20 13:14 data11.dat
-rw-------@ 1 christophemorisset  staff        16 Feb 25  2025 data11.dat.gz
-rw-------@ 1 christophemorisset  staff       148 Mar 20 13:17 data12.dat
-rw-------@ 1 christophemorisset  staff       148 Mar 20 11:50 data2.dat
-rw-------@ 1 christophemorisset  staff       165 Mar 20 12:34 data3.dat
-rw-------@ 1 christophemorisset  staff      1188 Mar 20 12:56 data4.dat
-rw-------@ 1 christophemorisset  staff      1186 Mar 20 13:02 data5.dat
-rw-------@ 1 christophemorisset  staff      1187 Mar 31  2025 data6.dat
-rw-------@ 1 christophemorisset  staff       364 Mar 23 10:56 data7.dat
-rw-------@ 1 christophemorisset  staff       298 Feb 11  2025 dcumsum.f
-rw-------@ 1 christophemorisset  staff       294 May 13  2025 env_FH_Python_Lecture_ML.yml
-rw-------@ 1 christophemorisset  staff      1344 Feb 17 13:37 ex1.html
-rw-------@ 1 christophemorisset  staff       159 Feb 17 12:56 ex1.py
-rw-------@ 1 christophemorisset  staff      6319 Feb 11  2025 grep3.py
-rw-------@ 1 christophemorisset  staff        49 Feb 11  2025 hello.py
-rw-------@ 1 christophemorisset  staff      1090 Feb 11  2025 hellofortran.c
-rw-------@ 1 christophemorisset  staff       178 Feb 11  2025 hellofortran.f
-rw-------@ 1 christophemorisset  staff     33976 Feb 11  2025 hellofortran.so
-rw-------@ 1 christophemorisset  staff       150 Feb 11  2025 index.html
-rw-------@ 1 christophemorisset  staff   5789181 Apr 14 14:12 intro_Matplotlib.ipynb
-rw-------@ 1 christophemorisset  staff   1677612 Feb 11  2025 intro_Matplotlib.pdf
-rw-------@ 1 christophemorisset  staff    326924 Feb 11  2025 intro_Python.html
-rw-------@ 1 christophemorisset  staff    117119 Mar  3 10:23 intro_Python.ipynb
-rw-------@ 1 christophemorisset  staff    119242 Feb 11  2025 intro_Python.pdf
-rw-------@ 1 christophemorisset  staff    998960 Apr 21 15:22 intro_Scipy.ipynb
-rw-------@ 1 christophemorisset  staff    683346 Feb 11  2025 intro_Scipy.pdf
-rw-------@ 1 christophemorisset  staff    127341 Mar 19 13:29 intro_numpy.ipynb
-rw-------@ 1 christophemorisset  staff    128064 Feb 11  2025 intro_numpy.pdf
drwx------@ 3 christophemorisset  staff        96 Jan 25 00:28 mastDownload
-rw-------@ 1 christophemorisset  staff   8830080 Feb 11  2025 n10017o.fits
-rw-------@ 1 christophemorisset  staff      5760 Feb 25  2025 new.fits
-rw-------@ 1 christophemorisset  staff   1779169 May  9  2025 profile.html
-rw-------@ 1 christophemorisset  staff    180869 May  9  2025 profile.json
-rw-------@ 1 christophemorisset  staff    435801 Feb 11  2025 query_res.dat
-rw-------@ 1 christophemorisset  staff   1538466 Apr 14 13:47 scatter.pdf
-rw-------@ 1 christophemorisset  staff    135367 Apr 14 13:47 scatter.png
-rw-------@ 1 christophemorisset  staff    905924 Apr 14 13:47 scatter3.png
-rw-------@ 1 christophemorisset  staff   3892934 May  5  2025 sdss.csv.gz
-rw-------@ 1 christophemorisset  staff   1059840 Feb 11  2025 swp04345.mxhi
-rw-------@ 1 christophemorisset  staff        47 May  9  2025 sys_text.py
-rw-------@ 1 christophemorisset  staff       354 Mar 24  2025 tab1.dat
-rw-------@ 1 christophemorisset  staff       668 May  5  2025 tab_cds1.ascii
-rw-------@ 1 christophemorisset  staff     43200 Feb 11  2025 tab_cds1.fits
-rw-------@ 1 christophemorisset  staff      1334 Mar 24  2025 tab_cds1.tex
-rw-------@ 1 christophemorisset  staff      1826 May  5  2025 tab_cds2.ascii
-rw-------@ 1 christophemorisset  staff       455 Mar 31  2025 table.html
-rw-------@ 1 christophemorisset  staff      6728 May  9  2025 test_1_prof.py
-rw-------@ 1 christophemorisset  staff      6552 Apr 21  2025 test_2_err.py
-rw-------@ 1 christophemorisset  staff      6527 Apr 21  2025 test_4.py
-rw-------@ 1 christophemorisset  staff       166 May  9  2025 test_me.py
-rw-------@ 1 christophemorisset  staff       318 Apr 22  2025 test_pyneb.py

If you do not want to wait untill the command finishes, use Popen. It starts the command, and communicate() is transmiting the response of the command.

In [13]:
command = 'ls -l'
popen = subprocess.Popen(command, shell=True)
print(popen)

<Popen: returncode: None args: 'ls -l'>

In [14]:
popen = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True)
res = popen.communicate()[0]
print(type(res))
print('-'*20)
print(res)
print('-'*20)
print(res.decode())

<class 'bytes'>
--------------------
b'total 132848\n-rw-------@ 1 christophemorisset  staff     89353 Apr 21  2025 \x1b[30m\x1b[47m0040000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     85600 Apr 22  2025 \x1b[30m\x1b[47m0050000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     86018 May  9  2025 \x1b[30m\x1b[47m0050000_7.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     86741 Apr 22  2025 \x1b[30m\x1b[47m0060000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     88843 Apr 22  2025 \x1b[30m\x1b[47m0070000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     89360 Apr 22  2025 \x1b[30m\x1b[47m0080000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     89971 Apr 21  2025 \x1b[30m\x1b[47m0090000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     89722 Apr 22  2025 \x1b[30m\x1b[47m0100000_5.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     90544 Apr 22  2025 \x1b[30m\x1b[47m0100000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     91192 Apr 22  2025 \x1b[30m\x1b[47m0100000_7.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     91475 Apr 22  2025 \x1b[30m\x1b[47m0100000_8.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     90430 Apr 22  2025 \x1b[30m\x1b[47m0110000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     90960 May  9  2025 \x1b[30m\x1b[47m0110000_7.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     89525 Apr 22  2025 \x1b[30m\x1b[47m0120000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     89899 Apr 22  2025 \x1b[30m\x1b[47m0130000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     89170 Apr 21  2025 \x1b[30m\x1b[47m0140000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     89263 Apr 22  2025 \x1b[30m\x1b[47m0150000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     88929 Apr 22  2025 \x1b[30m\x1b[47m0160000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     88991 Apr 22  2025 \x1b[30m\x1b[47m0170000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     88780 Apr 22  2025 \x1b[30m\x1b[47m0180000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     89075 Apr 22  2025 \x1b[30m\x1b[47m0180000_7.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff     88591 Apr 21  2025 \x1b[30m\x1b[47m0190000_6.00_33_50_02_15.bin_0.1.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff    960204 May 14  2025 ANN.ipynb\n-rw-------@ 1 christophemorisset  staff    173771 May  5  2025 ANN_1_2.png\n-rw-------@ 1 christophemorisset  staff     20137 Feb 11  2025 Calling Fortran.ipynb\n-rw-------@ 1 christophemorisset  staff     86815 Feb 11  2025 Calling Fortran.pdf\n-rw-------@ 1 christophemorisset  staff   3892947 Mar 26 11:50 DR9_photo-z-small.csv.gz\n-rw-------@ 1 christophemorisset  staff       217 Feb 25  2025 \x1b[30m\x1b[47mDemo.pickle\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       194 Feb 25  2025 \x1b[30m\x1b[47mDemo.pklz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       445 Feb 11  2025 Evaluacion.ipynb\n-rw-------@ 1 christophemorisset  staff    120910 Apr 14 13:47 \x1b[30m\x1b[47mFig1.pdf\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff   2466314 May 20  2025 Galaxies_classification.ipynb\n-rw-------@ 1 christophemorisset  staff   1177040 Feb 11  2025 \x1b[30m\x1b[47mHII.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff    853215 Feb 11  2025 InstallPython.key\n-rw-------@ 1 christophemorisset  staff    716796 Apr 14 14:12 Interact with files.ipynb\n-rw-------@ 1 christophemorisset  staff    432747 Feb 11  2025 Interact with files.pdf\n-rw-------@ 1 christophemorisset  staff    131497 Feb 11  2025 Intro_1.odp\n-rw-------@ 1 christophemorisset  staff    174202 Feb 11  2025 Intro_1.pdf\n-rw-------@ 1 christophemorisset  staff   1477306 Feb 11  2025 Machine Learning.pdf\n-rw-------@ 1 christophemorisset  staff     52571 Apr 28  2025 MySQL.odp\n-rw-------@ 1 christophemorisset  staff    104600 Apr 28  2025 MySQL.pdf\n-rw-------@ 1 christophemorisset  staff   1332565 May  9  2025 OOP.ipynb\n-rw-------@ 1 christophemorisset  staff    536767 Feb 11  2025 OOP.pdf\n-rw-------@ 1 christophemorisset  staff     81850 May  9  2025 Optimization.ipynb\n-rw-------@ 1 christophemorisset  staff    481656 Feb 11  2025 Optimization.pdf\n-rw-------@ 1 christophemorisset  staff      2537 Feb 11  2025 Parallel.ipynb\n-rw-------@ 1 christophemorisset  staff   1679352 May 13  2025 Redshifts.ipynb\n-rw-------@ 1 christophemorisset  staff    999554 May  5  2025 Redshifts_ai4neb.ipynb\n-rw-------@ 1 christophemorisset  staff      1434 Feb 11  2025 \x1b[30m\x1b[47mTest-Install.ipynb\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff    126026 Apr 28 14:36 Useful_libraries.ipynb\n-rw-------@ 1 christophemorisset  staff    514073 Feb 11  2025 Useful_libraries.pdf\n-rw-------@ 1 christophemorisset  staff    207646 May  9  2025 Using_SQLalchemy.ipynb\n-rw-------@ 1 christophemorisset  staff     80302 Feb 11  2025 Using_SQLalchemy.pdf\n-rw-------@ 1 christophemorisset  staff    293519 May  9  2025 Using_astropy.ipynb\n-rw-------@ 1 christophemorisset  staff    208399 Feb 11  2025 Using_astropy.pdf\n-rw-------@ 1 christophemorisset  staff    165828 May  9  2025 Using_astroquery.ipynb\n-rw-------@ 1 christophemorisset  staff    120503 Apr 28  2025 Using_astroquery.pdf\ndrwx------@ 6 christophemorisset  staff       192 Jan 25 00:28 \x1b[34m__pycache__\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       114 Apr 21  2025 call_test_2_err.py\n-rw-------@ 1 christophemorisset  staff  14794880 Feb 11  2025 cosmo-early.npy\n-rw-------@ 1 christophemorisset  staff  14794880 Feb 11  2025 cosmo-late.npy\n-rw-------@ 1 christophemorisset  staff        65 Mar 20 11:21 \x1b[30m\x1b[47mdata1.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff        14 Feb 25  2025 \x1b[30m\x1b[47mdata10.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff        32 Mar 20 13:14 \x1b[30m\x1b[47mdata11.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff        16 Feb 25  2025 \x1b[30m\x1b[47mdata11.dat.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       148 Mar 20 13:17 \x1b[30m\x1b[47mdata12.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       148 Mar 20 11:50 \x1b[30m\x1b[47mdata2.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       165 Mar 20 12:34 \x1b[30m\x1b[47mdata3.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff      1188 Mar 20 12:56 \x1b[30m\x1b[47mdata4.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff      1186 Mar 20 13:02 \x1b[30m\x1b[47mdata5.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff      1187 Mar 31  2025 \x1b[30m\x1b[47mdata6.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       364 Mar 23 10:56 \x1b[30m\x1b[47mdata7.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       298 Feb 11  2025 dcumsum.f\n-rw-------@ 1 christophemorisset  staff       294 May 13  2025 env_FH_Python_Lecture_ML.yml\n-rw-------@ 1 christophemorisset  staff      1344 Feb 17 13:37 \x1b[30m\x1b[47mex1.html\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       159 Feb 17 12:56 \x1b[30m\x1b[47mex1.py\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff      6319 Feb 11  2025 grep3.py\n-rw-------@ 1 christophemorisset  staff        49 Feb 11  2025 hello.py\n-rw-------@ 1 christophemorisset  staff      1090 Feb 11  2025 hellofortran.c\n-rw-------@ 1 christophemorisset  staff       178 Feb 11  2025 hellofortran.f\n-rw-------@ 1 christophemorisset  staff     33976 Feb 11  2025 \x1b[30m\x1b[47mhellofortran.so\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       150 Feb 11  2025 index.html\n-rw-------@ 1 christophemorisset  staff   5789181 Apr 14 14:12 intro_Matplotlib.ipynb\n-rw-------@ 1 christophemorisset  staff   1677612 Feb 11  2025 intro_Matplotlib.pdf\n-rw-------@ 1 christophemorisset  staff    326924 Feb 11  2025 intro_Python.html\n-rw-------@ 1 christophemorisset  staff    117119 Mar  3 10:23 intro_Python.ipynb\n-rw-------@ 1 christophemorisset  staff    119242 Feb 11  2025 intro_Python.pdf\n-rw-------@ 1 christophemorisset  staff    998960 Apr 21 15:22 intro_Scipy.ipynb\n-rw-------@ 1 christophemorisset  staff    683346 Feb 11  2025 intro_Scipy.pdf\n-rw-------@ 1 christophemorisset  staff    127341 Mar 19 13:29 intro_numpy.ipynb\n-rw-------@ 1 christophemorisset  staff    128064 Feb 11  2025 intro_numpy.pdf\ndrwx------@ 3 christophemorisset  staff        96 Jan 25 00:28 \x1b[34mmastDownload\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff   8830080 Feb 11  2025 n10017o.fits\n-rw-------@ 1 christophemorisset  staff      5760 Feb 25  2025 new.fits\n-rw-------@ 1 christophemorisset  staff   1779169 May  9  2025 \x1b[30m\x1b[47mprofile.html\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff    180869 May  9  2025 \x1b[30m\x1b[47mprofile.json\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff    435801 Feb 11  2025 \x1b[30m\x1b[47mquery_res.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff   1538466 Apr 14 13:47 \x1b[30m\x1b[47mscatter.pdf\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff    135367 Apr 14 13:47 \x1b[30m\x1b[47mscatter.png\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff    905924 Apr 14 13:47 \x1b[30m\x1b[47mscatter3.png\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff   3892934 May  5  2025 \x1b[30m\x1b[47msdss.csv.gz\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff   1059840 Feb 11  2025 swp04345.mxhi\n-rw-------@ 1 christophemorisset  staff        47 May  9  2025 sys_text.py\n-rw-------@ 1 christophemorisset  staff       354 Mar 24  2025 \x1b[30m\x1b[47mtab1.dat\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       668 May  5  2025 tab_cds1.ascii\n-rw-------@ 1 christophemorisset  staff     43200 Feb 11  2025 tab_cds1.fits\n-rw-------@ 1 christophemorisset  staff      1334 Mar 24  2025 tab_cds1.tex\n-rw-------@ 1 christophemorisset  staff      1826 May  5  2025 tab_cds2.ascii\n-rw-------@ 1 christophemorisset  staff       455 Mar 31  2025 table.html\n-rw-------@ 1 christophemorisset  staff      6728 May  9  2025 \x1b[30m\x1b[47mtest_1_prof.py\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff      6552 Apr 21  2025 \x1b[30m\x1b[47mtest_2_err.py\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff      6527 Apr 21  2025 \x1b[30m\x1b[47mtest_4.py\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       166 May  9  2025 \x1b[30m\x1b[47mtest_me.py\x1b[m\x1b[m\n-rw-------@ 1 christophemorisset  staff       318 Apr 22  2025 \x1b[30m\x1b[47mtest_pyneb.py\x1b[m\x1b[m\n'
--------------------
total 132848
-rw-------@ 1 christophemorisset  staff     89353 Apr 21  2025 0040000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     85600 Apr 22  2025 0050000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     86018 May  9  2025 0050000_7.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     86741 Apr 22  2025 0060000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     88843 Apr 22  2025 0070000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89360 Apr 22  2025 0080000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89971 Apr 21  2025 0090000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89722 Apr 22  2025 0100000_5.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     90544 Apr 22  2025 0100000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     91192 Apr 22  2025 0100000_7.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     91475 Apr 22  2025 0100000_8.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     90430 Apr 22  2025 0110000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     90960 May  9  2025 0110000_7.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89525 Apr 22  2025 0120000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89899 Apr 22  2025 0130000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89170 Apr 21  2025 0140000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89263 Apr 22  2025 0150000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     88929 Apr 22  2025 0160000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     88991 Apr 22  2025 0170000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     88780 Apr 22  2025 0180000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     89075 Apr 22  2025 0180000_7.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff     88591 Apr 21  2025 0190000_6.00_33_50_02_15.bin_0.1.gz
-rw-------@ 1 christophemorisset  staff    960204 May 14  2025 ANN.ipynb
-rw-------@ 1 christophemorisset  staff    173771 May  5  2025 ANN_1_2.png
-rw-------@ 1 christophemorisset  staff     20137 Feb 11  2025 Calling Fortran.ipynb
-rw-------@ 1 christophemorisset  staff     86815 Feb 11  2025 Calling Fortran.pdf
-rw-------@ 1 christophemorisset  staff   3892947 Mar 26 11:50 DR9_photo-z-small.csv.gz
-rw-------@ 1 christophemorisset  staff       217 Feb 25  2025 Demo.pickle
-rw-------@ 1 christophemorisset  staff       194 Feb 25  2025 Demo.pklz
-rw-------@ 1 christophemorisset  staff       445 Feb 11  2025 Evaluacion.ipynb
-rw-------@ 1 christophemorisset  staff    120910 Apr 14 13:47 Fig1.pdf
-rw-------@ 1 christophemorisset  staff   2466314 May 20  2025 Galaxies_classification.ipynb
-rw-------@ 1 christophemorisset  staff   1177040 Feb 11  2025 HII.dat
-rw-------@ 1 christophemorisset  staff    853215 Feb 11  2025 InstallPython.key
-rw-------@ 1 christophemorisset  staff    716796 Apr 14 14:12 Interact with files.ipynb
-rw-------@ 1 christophemorisset  staff    432747 Feb 11  2025 Interact with files.pdf
-rw-------@ 1 christophemorisset  staff    131497 Feb 11  2025 Intro_1.odp
-rw-------@ 1 christophemorisset  staff    174202 Feb 11  2025 Intro_1.pdf
-rw-------@ 1 christophemorisset  staff   1477306 Feb 11  2025 Machine Learning.pdf
-rw-------@ 1 christophemorisset  staff     52571 Apr 28  2025 MySQL.odp
-rw-------@ 1 christophemorisset  staff    104600 Apr 28  2025 MySQL.pdf
-rw-------@ 1 christophemorisset  staff   1332565 May  9  2025 OOP.ipynb
-rw-------@ 1 christophemorisset  staff    536767 Feb 11  2025 OOP.pdf
-rw-------@ 1 christophemorisset  staff     81850 May  9  2025 Optimization.ipynb
-rw-------@ 1 christophemorisset  staff    481656 Feb 11  2025 Optimization.pdf
-rw-------@ 1 christophemorisset  staff      2537 Feb 11  2025 Parallel.ipynb
-rw-------@ 1 christophemorisset  staff   1679352 May 13  2025 Redshifts.ipynb
-rw-------@ 1 christophemorisset  staff    999554 May  5  2025 Redshifts_ai4neb.ipynb
-rw-------@ 1 christophemorisset  staff      1434 Feb 11  2025 Test-Install.ipynb
-rw-------@ 1 christophemorisset  staff    126026 Apr 28 14:36 Useful_libraries.ipynb
-rw-------@ 1 christophemorisset  staff    514073 Feb 11  2025 Useful_libraries.pdf
-rw-------@ 1 christophemorisset  staff    207646 May  9  2025 Using_SQLalchemy.ipynb
-rw-------@ 1 christophemorisset  staff     80302 Feb 11  2025 Using_SQLalchemy.pdf
-rw-------@ 1 christophemorisset  staff    293519 May  9  2025 Using_astropy.ipynb
-rw-------@ 1 christophemorisset  staff    208399 Feb 11  2025 Using_astropy.pdf
-rw-------@ 1 christophemorisset  staff    165828 May  9  2025 Using_astroquery.ipynb
-rw-------@ 1 christophemorisset  staff    120503 Apr 28  2025 Using_astroquery.pdf
drwx------@ 6 christophemorisset  staff       192 Jan 25 00:28 __pycache__
-rw-------@ 1 christophemorisset  staff       114 Apr 21  2025 call_test_2_err.py
-rw-------@ 1 christophemorisset  staff  14794880 Feb 11  2025 cosmo-early.npy
-rw-------@ 1 christophemorisset  staff  14794880 Feb 11  2025 cosmo-late.npy
-rw-------@ 1 christophemorisset  staff        65 Mar 20 11:21 data1.dat
-rw-------@ 1 christophemorisset  staff        14 Feb 25  2025 data10.dat
-rw-------@ 1 christophemorisset  staff        32 Mar 20 13:14 data11.dat
-rw-------@ 1 christophemorisset  staff        16 Feb 25  2025 data11.dat.gz
-rw-------@ 1 christophemorisset  staff       148 Mar 20 13:17 data12.dat
-rw-------@ 1 christophemorisset  staff       148 Mar 20 11:50 data2.dat
-rw-------@ 1 christophemorisset  staff       165 Mar 20 12:34 data3.dat
-rw-------@ 1 christophemorisset  staff      1188 Mar 20 12:56 data4.dat
-rw-------@ 1 christophemorisset  staff      1186 Mar 20 13:02 data5.dat
-rw-------@ 1 christophemorisset  staff      1187 Mar 31  2025 data6.dat
-rw-------@ 1 christophemorisset  staff       364 Mar 23 10:56 data7.dat
-rw-------@ 1 christophemorisset  staff       298 Feb 11  2025 dcumsum.f
-rw-------@ 1 christophemorisset  staff       294 May 13  2025 env_FH_Python_Lecture_ML.yml
-rw-------@ 1 christophemorisset  staff      1344 Feb 17 13:37 ex1.html
-rw-------@ 1 christophemorisset  staff       159 Feb 17 12:56 ex1.py
-rw-------@ 1 christophemorisset  staff      6319 Feb 11  2025 grep3.py
-rw-------@ 1 christophemorisset  staff        49 Feb 11  2025 hello.py
-rw-------@ 1 christophemorisset  staff      1090 Feb 11  2025 hellofortran.c
-rw-------@ 1 christophemorisset  staff       178 Feb 11  2025 hellofortran.f
-rw-------@ 1 christophemorisset  staff     33976 Feb 11  2025 hellofortran.so
-rw-------@ 1 christophemorisset  staff       150 Feb 11  2025 index.html
-rw-------@ 1 christophemorisset  staff   5789181 Apr 14 14:12 intro_Matplotlib.ipynb
-rw-------@ 1 christophemorisset  staff   1677612 Feb 11  2025 intro_Matplotlib.pdf
-rw-------@ 1 christophemorisset  staff    326924 Feb 11  2025 intro_Python.html
-rw-------@ 1 christophemorisset  staff    117119 Mar  3 10:23 intro_Python.ipynb
-rw-------@ 1 christophemorisset  staff    119242 Feb 11  2025 intro_Python.pdf
-rw-------@ 1 christophemorisset  staff    998960 Apr 21 15:22 intro_Scipy.ipynb
-rw-------@ 1 christophemorisset  staff    683346 Feb 11  2025 intro_Scipy.pdf
-rw-------@ 1 christophemorisset  staff    127341 Mar 19 13:29 intro_numpy.ipynb
-rw-------@ 1 christophemorisset  staff    128064 Feb 11  2025 intro_numpy.pdf
drwx------@ 3 christophemorisset  staff        96 Jan 25 00:28 mastDownload
-rw-------@ 1 christophemorisset  staff   8830080 Feb 11  2025 n10017o.fits
-rw-------@ 1 christophemorisset  staff      5760 Feb 25  2025 new.fits
-rw-------@ 1 christophemorisset  staff   1779169 May  9  2025 profile.html
-rw-------@ 1 christophemorisset  staff    180869 May  9  2025 profile.json
-rw-------@ 1 christophemorisset  staff    435801 Feb 11  2025 query_res.dat
-rw-------@ 1 christophemorisset  staff   1538466 Apr 14 13:47 scatter.pdf
-rw-------@ 1 christophemorisset  staff    135367 Apr 14 13:47 scatter.png
-rw-------@ 1 christophemorisset  staff    905924 Apr 14 13:47 scatter3.png
-rw-------@ 1 christophemorisset  staff   3892934 May  5  2025 sdss.csv.gz
-rw-------@ 1 christophemorisset  staff   1059840 Feb 11  2025 swp04345.mxhi
-rw-------@ 1 christophemorisset  staff        47 May  9  2025 sys_text.py
-rw-------@ 1 christophemorisset  staff       354 Mar 24  2025 tab1.dat
-rw-------@ 1 christophemorisset  staff       668 May  5  2025 tab_cds1.ascii
-rw-------@ 1 christophemorisset  staff     43200 Feb 11  2025 tab_cds1.fits
-rw-------@ 1 christophemorisset  staff      1334 Mar 24  2025 tab_cds1.tex
-rw-------@ 1 christophemorisset  staff      1826 May  5  2025 tab_cds2.ascii

In [17]:
popen = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True)
res = popen.communicate()[0]
for line in res.decode().split('\n'):
    lspl = line.split()
    if len(lspl)> 4:
        if int(lspl[4]) > 1024**2:
            print(f"{lspl[8]:30s} -> {lspl[4]}")

DR9_photo-z-small.csv.gz       -> 3892947
Galaxies_classification.ipynb  -> 2466314
HII.dat        -> 1177040
Machine                        -> 1477306
OOP.ipynb                      -> 1332565
Redshifts.ipynb                -> 1679352
cosmo-early.npy                -> 14794880
cosmo-late.npy                 -> 14794880
intro_Matplotlib.ipynb         -> 5789181
intro_Matplotlib.pdf           -> 1677612
n10017o.fits                   -> 8830080
profile.html   -> 1779169
scatter.pdf    -> 1538466
sdss.csv.gz    -> 3892934
swp04345.mxhi                  -> 1059840

### re

The re module provides regular expression tools for advanced string processing. For complex matching and manipulation, regular expressions offer succinct, optimized solutions:

More in https://docs.python.org/3/library/re.html

In [20]:
import re
text = 'whifch fo7t or hand   Fell f fastest'
# Search the words starting with "f"
matches = re.findall(r'\bf[a-z]*', text)
print(matches)
matches = re.findall(r'\b[fF]\w*', text)
print(matches)

['fo', 'f', 'fastest']
['fo7t', 'Fell', 'f', 'fastest']

In [47]:
# Remove duplicate words
text = 'cat in the the hat the'
print(re.sub(r'(\b[a-z]+) \1', r'\1', text))

cat in the hat the

### urllib

In [22]:
from urllib.request import urlopen

In [23]:
for line in urlopen('http://dev.on-rev.com/myip.irev'):
    print(line)
    if 'IP' in str(line):
        IP = str(line).split(':')[1][:-7]
print('-------')
print(IP)

b'<html>\n'
b'<body>\n'
b'<p>\n'
b'Remote IP Address:132.248.1.15</p>\n'
b'</body>\n'
b'</html>'
-------
132.248.1.15

### Tables with power: pandas at https://pandas.pydata.org/

Tutorials: 
* https://pandas.pydata.org/docs/user_guide/10min.html
* https://www.learndatasci.com/tutorials/python-pandas-tutorial-complete-introduction-for-beginners/

In [40]:
import pandas as pd

In [41]:
%%writefile data2.dat
# The following data are for test purpose
N    f   x   y type
1   2.3  6   8 star
22   3.5  7   9 galaxy
3  -4.2  5   7 cluster # comment
5  4.55 5 7 cluster
4  -10.5  5  7 star
4  -10.55  5  7 star
#4  -10.5  5  7 test

Overwriting data2.dat

In [78]:
# The N column is used as index. It is not mandatory to have an index defined, if not, pandas will create one.
df = pd.read_csv('data2.dat', comment='#', sep='\\s+', index_col = 'type')

In [79]:
df

          N      f  x  y
type
star      1   2.30  6  8
galaxy   22   3.50  7  9
cluster   3  -4.20  5  7
cluster   5   4.55  5  7
star      4 -10.50  5  7
star      4 -10.55  5  7

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, star to star
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   N       6 non-null      int64
 1   f       6 non-null      float64
 2   x       6 non-null      int64
 3   y       6 non-null      int64
dtypes: float64(1), int64(3)
memory usage: 240.0+ bytes

In [81]:
df.describe()  # only for numerical columns

               N          f        x        y
count   6.000000   6.000000  6.00000  6.00000
mean    6.500000  -2.483333  5.50000  7.50000
std     7.713624   6.934455  0.83666  0.83666
min     1.000000 -10.550000  5.00000  7.00000
25%     3.250000  -8.925000  5.00000  7.00000
50%     4.000000  -0.950000  5.00000  7.00000
75%     4.750000   3.200000  5.75000  7.75000
max    22.000000   4.550000  7.00000  9.00000

In [82]:
df['R'] = np.sqrt(df['x']**2 + df.y**2)

In [83]:
df['R']

type
star       10.000000
galaxy     11.401754
cluster     8.602325
cluster     8.602325
star        8.602325
star        8.602325
Name: R, dtype: float64

In [84]:
# index no needs to be unique
df.index

Index(['star', 'galaxy', 'cluster', 'cluster', 'star', 'star'], dtype='object', name='type')

In [85]:
# Access rows by the index
df.loc['star'].describe()

              N          f         x         y          R
count  3.000000   3.000000  3.000000  3.000000   3.000000
mean   3.000000  -6.250000  5.333333  7.333333   9.068217
std    1.732051   7.404559  0.577350  0.577350   0.806948
min    1.000000 -10.550000  5.000000  7.000000   8.602325
25%    2.500000 -10.525000  5.000000  7.000000   8.602325
50%    4.000000 -10.500000  5.000000  7.000000   8.602325
75%    4.000000  -4.100000  5.500000  7.500000   9.301163
max    4.000000   2.300000  6.000000  8.000000  10.000000

In [86]:
# Access rows by position
df.iloc[1::2]

          N      f  x  y          R
type
galaxy   22   3.50  7  9  11.401754
cluster   5   4.55  5  7   8.602325
star      4 -10.55  5  7   8.602325

In [87]:
df.iloc[4]['f']

-10.5

In [88]:
df

          N      f  x  y          R
type
star      1   2.30  6  8  10.000000
galaxy   22   3.50  7  9  11.401754
cluster   3  -4.20  5  7   8.602325
cluster   5   4.55  5  7   8.602325
star      4 -10.50  5  7   8.602325
star      4 -10.55  5  7   8.602325

In [89]:
mask = df['N'] == 4
mask_arr = mask.to_numpy()
print(mask)
print(mask_arr)

type
star       False
galaxy     False
cluster    False
cluster    False
star        True
star        True
Name: N, dtype: bool
[False False False False  True  True]

In [90]:
df.loc[mask,'N'] = 44

In [91]:
df

          N      f  x  y          R
type
star      1   2.30  6  8  10.000000
galaxy   22   3.50  7  9  11.401754
cluster   3  -4.20  5  7   8.602325
cluster   5   4.55  5  7   8.602325
star     44 -10.50  5  7   8.602325
star     44 -10.55  5  7   8.602325

In [92]:
df[mask]['R']

type
star    8.602325
star    8.602325
Name: R, dtype: float64

In [93]:
df.loc[mask,'R'].to_numpy()

array([8.60232527, 8.60232527])

In [94]:
coord_cols = ['x', 'y']
df.loc[mask, coord_cols].mean()

x    5.0
y    7.0
dtype: float64

In [95]:
df.columns

Index(['N', 'f', 'x', 'y', 'R'], dtype='object')

In [102]:
df.groupby('type')[['f', 'x', 'y']].apply(print)

            f  x  y
type
cluster -4.20  5  7
cluster  4.55  5  7
          f  x  y
type
galaxy  3.5  7  9
          f  x  y
type
star   2.30  6  8
star -10.50  5  7
star -10.55  5  7

Empty DataFrame
Columns: []
Index: []

In [100]:
df.groupby('type').mean()

                 N      f         x         y          R
type
cluster   4.000000  0.175  5.000000  7.000000   8.602325
galaxy   22.000000  3.500  7.000000  9.000000  11.401754
star     29.666667 -6.250  5.333333  7.333333   9.068217

In [104]:
df.groupby('type')[['f', 'x', 'y']].describe()

            f                                                            x  \
        count   mean       std    min      25%     50%     75%   max count
type
cluster   2.0  0.175  6.187184  -4.20  -2.0125   0.175  2.3625  4.55   2.0
galaxy    1.0  3.500       NaN   3.50   3.5000   3.500  3.5000  3.50   1.0
star      3.0 -6.250  7.404559 -10.55 -10.5250 -10.500 -4.1000  2.30   3.0

                   ...               y                                         \
             mean  ...  75%  max count      mean      std  min  25%  50%  75%
type               ...
cluster  5.000000  ...  5.0  5.0   2.0  7.000000  0.00000  7.0  7.0  7.0  7.0
galaxy   7.000000  ...  7.0  7.0   1.0  9.000000      NaN  9.0  9.0  9.0  9.0
star     5.333333  ...  5.5  6.0   3.0  7.333333  0.57735  7.0  7.0  7.0  7.5


         max
type
cluster  7.0
galaxy   9.0
star     8.0

[3 rows x 24 columns]